--// rooms.ini converted into a roblox-like format

local RoomsModule = {}

local RoomsFolder = script.Parent

RoomsModule.rooms = {
	roomambience = {
		name = "room ambience",
		ambience7 = "895.ogg",
		ambience5 = "drip.ogg",
		ambience10 = "servers1.ogg",
		ambience6 = "SFX\Alarm\Alarm.ogg",
		ambience1 = "rumble.ogg",
		ambience3 = "pulsing.ogg",
		ambience8 = "fuelpump.ogg",
		ambience9 = "Fan.ogg",
		ambience4 = "ventilation.ogg",
		ambience2 = "lowdrone.ogg",
	},
	
	-- LIGHT CONTAINMENT ZONE ROOMS
	-- ============================
	
	lockroom = {
		name = "lockroom",
		path = "GFX\map\lockroom_opt.rmesh",
		zone2 = 3,
		zone1 = 1,
		commonness = 30,
		shape = "2C",
		descr = "A timed airlock room, with two doors.",
	},
	["173"] = {
		name = "173",
		path = "GFX\map\173bright_opt.rmesh",
		--disabledecals = true,
		commonness = 0,
		shape = "1",
		descr = "Class-D Cells & SCP-173's chamber in the intro. Placed automatically in all maps.",
		disableoverlapcheck = true
	},
	start = {
		name = "start",
		path = "GFX\map\173_opt.rmesh",
		--disabledecals = true,
		commonness = 0,
		shape = "1",
		descr = "SCP-173's chamber, after the breach. Placed automatically in all maps.",
		disableoverlapcheck = true
	},
	room1123 = {
		name = "room1123",
		path = "GFX\map\1123_opt.rmesh",
		zone1 = 1,
		--disabledecals = true,
		commonness = 0,
		shape = "2",
		descr = "SCP-1123's containment chamber.",
	},
	room1archive = {
		name = "room1archive",
		path = "GFX\map\room1archive_opt.rmesh",
		zone1 = 1,
		commonness = 80,
		shape = "1",
		descr = "An archive room, where various (random) items spawn on shelves.",
	},
	room2storage = {
		name = "room2storage",
		path = "GFX\map\room2storage_opt.rmesh",
		zone1 = 1,
		--disabledecals = true,
		commonness = 0,
		shape = "2",
		descr = "SCP-970's storage hallway.",
	},
	room3storage = {
		name = "room3storage",
		path = "GFX\map\room3storage_opt.rmesh",
		zone1 = 1,
		disableoverlapcheck = true,
		commonness = 0,
		shape = "3",
		descr = "SCP-939's storage area, with various roaming instances of 939.",
	},
	room2tesla_lcz = {
		name = "room2tesla_lcz",
		path = "GFX\map\room2tesla_lcz_opt.rmesh",
		zone1 = 1,
		commonness = 100,
		shape = "2",
		descr = "Hallway with a tesla gate. LCZ variant.",
	},
	endroom = {
		name = "endroom",
		path = "GFX\map\endroom_opt.rmesh",
		zone1 = 1,
		commonness = 100,
		shape = "1",
		descr = "Red-lit dead end room with a large, unopenable gate.",
	},
	room012 = {
		name = "room012",
		path = "GFX\map\room012_opt.rmesh",
		zone1 = 1,
		--disabledecals = true,
		commonness = 0,
		shape = "2",
		descr = "SCP-012's containment chamber.",
	},
	room205 = {
		name = "room205",
		path = "GFX\map\room205_opt.rmesh",
		large = true,
		zone1 = 1,
		commonness = 0,
		shape = "1",
		descr = "SCP-205's containment chamber.",
	},
	room2 = {
		name = "room2",
		path = "GFX\map\room2_opt.rmesh",
		zone1 = 1,
		commonness = 45,
		shape = "2",
		descr = "An empty, two-door hallway.",
	},
	room2_2 = {
		name = "room2_2",
		path = "GFX\map\room2_2_opt.rmesh",
		zone1 = 1,
		commonness = 40,
		shape = "2",
		descr = "An empty, two-door hallway with a large fan/vent in the wall.",
	},
	room2_3 = {
		name = "room2_3",
		path = "GFX\map\room2_3_opt.rmesh",
		zone1 = 1,
		commonness = 35,
		shape = "2",
		descr = "A larger version of the two-door hallway, with lights in the floor.",
	},
	room2_4 = {
		name = "room2_4",
		path = "GFX\map\room2_4_opt.rmesh",
		zone1 = 1,
		commonness = 30,
		shape = "2",
		descr = "A two-door hallway, with a unopenable door off to the side.",
	},
	room2_5 = {
		name = "room2_5",
		path = "GFX\map\room2_5_opt.rmesh",
		zone1 = 1,
		commonness = 35,
		shape = "2",
		descr = "A two-door hallway, with lowered ceilings.",
	},
	room2C = {
		name = "room2C",
		path = "GFX\map\room2C_opt.rmesh",
		zone1 = 1,
		commonness = 40,
		shape = "2C",
		descr = "An empty, plain corner room.",
	},
	room2c2 = {
		name = "room2c2",
		path = "GFX\map\room2c2_opt.rmesh",
		zone1 = 1,
		commonness = 30,
		shape = "2C",
		descr = "A corner room, with more of a LCZ style.",
	},
	room2closets = {
		name = "room2closets",
		path = "GFX\map\room2closets_opt.rmesh",
		large = true,
		zone1 = 1,
		--disabledecals = true,
		commonness = 0,
		shape = "2",
		descr = "A storage hallway, where SCP-173 kills two NPCs. The Gas Mask & Batteries spawn here.",
	},
	room2elevator = {
		name = "room2elevator",
		path = "GFX\map\room2elevator_opt.rmesh",
		zone1 = 1,
		commonness = 20,
		shape = "2",
		descr = "A two-door hallway, with an elevator off to the side.",
	},
	room2doors = {
		name = "room2doors",
		path = "GFX\map\room2doors_opt.rmesh",
		zone1 = 1,
		commonness = 30,
		shape = "2",
		descr = "Red-lit airlock room, in the shape of a T.",
	},
	room2scps = {
		name = "room2scps",
		path = "GFX\map\room2scps_opt.rmesh",
		zone1 = 1,
		commonness = 0,
		shape = "2",
		descr = "SCP-714's, SCP-860's, & SCP-1025's two-door hallway.",
	},
	room860 = {
		name = "room860",
		path = "GFX\map\room860_opt.rmesh",
		commonness = 0,
		shape = "2",
		descr = "SCP-860-1's containment chamber. Can't be traversed without SCP-860.",
	},
	room2testroom2 = {
		name = "room2testroom2",
		path = "GFX\map\room2testroom2_opt.rmesh",
		zone1 = 1,
		commonness = 0,
		shape = "2",
		descr = "Two-door hallway with a small testing room, where SCP-173 shatters the testroom's window.",
	},
	room3 = {
		name = "room3",
		path = "GFX\map\room3_opt.rmesh",
		zone1 = 1,
		commonness = 100,
		shape = "3",
		descr = "Three-door hallway, with a caged off portion in the back wall.",
	},
	room3_2 = {
		name = "room3_2",
		path = "GFX\map\room3_2_opt.rmesh",
		zone1 = 1,
		commonness = 100,
		shape = "3",
		descr = "A three-door hallway, without the caged portion.",
	},
	room4 = {
		name = "room4",
		path = "GFX\map\room4_opt.rmesh",
		zone1 = 1,
		commonness = 100,
		shape = "4",
		descr = "A four-door hallway, with a metal walkway hanging above.",
	},
	room4_2 = {
		name = "room4_2",
		path = "GFX\map\room4_2_opt.rmesh",
		zone1 = 1,
		commonness = 80,
		shape = "4",
		descr = "A varient of the four-door hallway, without the metal walkway.",
	},
	roompj = {
		name = "roompj",
		path = "GFX\map\roompj_opt.rmesh",
		zone1 = 1,
		--disabledecals = true,
		commonness = 0,
		shape = "1",
		descr = "SCP-372's containment chamber.",
	},
	["914"] = {
		name = "914",
		path = "GFX\map\machineroom_opt.rmesh",
		zone1 = 1,
		commonness = 0,
		shape = "1",
		descr = "SCP-914's containment chamber.",
	},
	room2gw = {
		name = "room2gw",
		path = "GFX\map\room2gw_opt.rmesh",
		zone1 = 1,
		commonness = 10,
		shape = "2",
		descr = "A two-door contamination airlock.",
	},
	room2gw_b = {
		name = "room2gw_b",
		path = "GFX\map\room2gw_b_opt.rmesh",
		zone1 = 1,
		commonness = 0,
		shape = "2",
		descr = "Broken varient of the two-door contamination airlock.",
	},
	room1162 = {
		name = "room1162",
		path = "GFX\map\room1162_opt.rmesh",
		zone1 = 1,
		commonness = 0,
		shape = "2C",
		descr = "SCP-1162's containment chamber, in a corner room.",
	},
	room2scps2 = {
		name = "room2scps2",
		path = "GFX\map\room2scps2_opt.rmesh",
		zone1 = 1,
		commonness = 0,
		shape = "2",
		descr = "SCP-1499 & SCP-500's containment chambers, in a two-door hallway.",
	},
	room2sl = {
		name = "room2sl",
		path = "GFX\map\room2sl_opt.rmesh",
		large = true,
		zone1 = 1,
		commonness = 0,
		shape = "2",
		descr = "The surveillance room in the LCZ. Required for passing into HCZ, if used.",
	},
	lockroom3 = {
		name = "lockroom3",
		path = "GFX\map\lockroom3_opt.rmesh",
		zone1 = 1,
		commonness = 15,
		shape = "2C",
		descr = "A varient of the timed lockroom, where a seperate path is opened. The airlock itself is broken.",
	},
	room4info = {
		name = "room4info",
		path = "GFX\map\room4info_opt.rmesh",
		zone1 = 1,
		commonness = 0,
		shape = "4",
		descr = "A 4-way hallway containing an info center.",
	},
	room3_3 = {
		name = "room3_3",
		path = "GFX\map\room3_3_opt.rmesh",
		zone1 = 1,
		commonness = 20,
		shape = "3",
		descr = "Another variant of a three-door hallway.",
	},
	checkpoint1 = {
		name = "checkpoint1",
		path = "GFX\map\checkpoint1_opt.rmesh",
		commonness = 0,
		shape = "2",
		descr = "The keycarded checkpoint between the LCZ and HCZ.",
	},
	
	-- HEAVY CONTAINMENT ZONE ROOMS
	-- ============================
	
	["008"] = {
		name = "008",
		path = "GFX\map\008_opt.rmesh",
		zone1 = 2,
		--disabledecals = true,
		commonness = 0,
		shape = "1",
		descr = "SCP-008's containment chamber.",
	},
	room035 = {
		name = "room035",
		path = "GFX\map\room035_opt.rmesh",
		zone1 = 2,
		commonness = 0,
		shape = "1",
		descr = "SCP-035's containment chamber.",
	},
	room049 = {
		name = "room049",
		path = "GFX\map\room049_opt.rmesh",
		usevolumelighting = 1,
		disableoverlapcheck = true,
		walksound = 1,
		zone1 = 2,
		--disabledecals = true,
		commonness = 0,
		shape = "2",
		descr = "SCP-049's containment chamber.",
	},
	room106 = {
		name = "room106",
		path = "GFX\map\room106_opt.rmesh",
		large = true,
		zone1 = 2,
		--disabledecals = true,
		commonness = 0,
		shape = "1",
		descr = "SCP-106's containment chamber.",
	},
	room513 = {
		name = "room513",
		path = "GFX\map\room513_opt.rmesh",
		usevolumelighting = 1,
		zone1 = 2,
		commonness = 0,
		shape = "3",
		descr = "SCP-513's containment chamber.",
	},
	coffin = {
		name = "coffin",
		path = "GFX\map\coffin_opt.rmesh",
		zone1 = 2,
		walksound = 1,
		--disabledecals = true,
		commonness = 0,
		shape = "1",
		descr = "SCP-895's containment chamber.",
	},
	room966 = {
		name = "room966",
		path = "GFX\map\room966_opt.rmesh",
		usevolumelighting = 1,
		zone1 = 2,
		disableoverlapcheck = true,
		commonness = 0,
		shape = "3",
		descr = "SCP-966's containment chamber.",
	},
	endroom2 = {
		name = "endroom2",
		path = "GFX\map\endroom2_opt.rmesh",
		zone1 = 2,
		commonness = 100,
		shape = "1",
		descr = "A small, red-lit, HCZ-styled endroom.",
	},
	testroom = {
		name = "testroom",
		path = "GFX\map\testroom_opt.rmesh",
		zone1 = 2,
		walksound = 1,
		--disabledecals = true,
		commonness = 0,
		shape = "2",
		descr = "A large testroom, where SCP-682's document can be found.",
	},
	tunnel = {
		name = "tunnel",
		path = "GFX\map\tunnel_opt.rmesh",
		usevolumelighting = 1,
		zone1 = 2,
		walksound = 1,
		commonness = 100,
		shape = "2",
		descr = "A two-door hallway, in the shape of a tunnel.",
	},
	tunnel2 = {
		name = "tunnel2",
		path = "GFX\map\tunnel2_opt.rmesh",
		usevolumelighting = 1,
		zone1 = 2,
		walksound = 1,
		commonness = 70,
		shape = "2",
		descr = "A varient of the tunnel hallway, with a fuse box off to the side where SCP-173 spawns.",
	},
	room2Ctunnel = {
		name = "room2Ctunnel",
		path = "GFX\map\room2Ctunnel_opt.rmesh",
		usevolumelighting = 1,
		zone1 = 2,
		walksound = 1,
		commonness = 40,
		shape = "2C",
		descr = "A HCZ-styled corner room.",
	},
	room2nuke = {
		name = "room2nuke",
		path = "GFX\map\room2nuke_opt.rmesh",
		large = true,
		zone1 = 2,
		commonness = 0,
		shape = "2",
		descr = "A two-door hallway, with a room on the side which leads to the Omega & Alpha warheads.",
	},
	room2pipes = {
		name = "room2pipes",
		path = "GFX\map\room2pipes_opt.rmesh",
		zone1 = 2,
		walksound = 1,
		--disabledecals = true,
		commonness = 50,
		shape = "2",
		descr = "A two-door hallway, with caged floors and ceiling that contain various pipes. SCP-106 can appear out of the walls.",
	},
	room2pit = {
		name = "room2pit",
		path = "GFX\map\room2pit_opt.rmesh",
		zone1 = 2,
		walksound = 1,
		--disabledecals = true,
		commonness = 75,
		shape = "2",
		descr = "A two-door catwalk, where the catwalk spews gas.",
	},
	room3pit = {
		name = "room3pit",
		path = "GFX\map\room3pit_opt.rmesh",
		zone1 = 2,
		walksound = 1,
		--disabledecals = true,
		commonness = 100,
		shape = "3",
		descr = "A three-door walkway, with a large box-like structure in the back wall.",
	},
	room4pit = {
		name = "room4pit",
		path = "GFX\map\room4pit_opt.rmesh",
		zone1 = 2,
		commonness = 100,
		shape = "4",
		descr = "A four-door walkway, with a large cube-like stucture in the middle of the room.",
	},
	room2servers = {
		name = "room2servers",
		path = "GFX\map\room2servers_opt.rmesh",
		large = true,
		zone1 = 2,
		walksound = 1,
		commonness = 0,
		shape = "2",
		descr = "SCP-096's spawn area, where 096 kills a guard.",
	},
	room2shaft = {
		name = "room2shaft",
		path = "GFX\map\room2shaft_opt.rmesh",
		--disabledecals = true,
		commonness = 0,
		shape = "2",
		descr = "A two-door hallway, which has a non-functional elevator and the maintenance shaft.",
	},
	room2tunnel = {
		name = "room2tunnel",
		path = "GFX\map\room2tunnel_opt.rmesh",
		zone1 = 2,
		walksound = 1,
		--disabledecals = true,
		commonness = 0,
		shape = "2",
		descr = "A closed gate, and elevators leading to the maintenance tunnels. Gate can be opened if SCP-372's chamber is in the map for the code.",
	},
	room3tunnel = {
		name = "room3tunnel",
		path = "GFX\map\room3tunnel_opt.rmesh",
		usevolumelighting = 1,
		zone1 = 2,
		walksound = 1,
		commonness = 100,
		shape = "3",
		descr = "A three-door hallway, shaped after tunnels.",
	},
	room4tunnels = {
		name = "room4tunnels",
		path = "GFX\map\4tunnels_opt.rmesh",
		usevolumelighting = 1,
		zone1 = 2,
		walksound = 1,
		commonness = 100,
		shape = "4",
		descr = "A four-door hallway, shaped after tunnels.",
	},
	room2tesla_hcz = {
		name = "room2tesla_hcz",
		path = "GFX\map\room2tesla_hcz_opt.rmesh",
		zone1 = 2,
		commonness = 100,
		shape = "2",
		descr = "Hallway with a tesla gate. HCZ variant.",
	},
	room3z2 = {
		name = "room3z2",
		path = "GFX\map\room3z2_opt.rmesh",
		zone1 = 2,
		commonness = 100,
		shape = "3",
		descr = "A T-shaped, three-door hallway.",
	},
	room2cpit = {
		name = "room2cpit",
		path = "GFX\map\room2cpit_opt.rmesh",
		zone1 = 2,
		--disabledecals = true,
		commonness = 0,
		shape = "2C",
		descr = "A corner room, with a large cube-like stucture in the middle of the room.",
	},
	room2pipes2 = {
		name = "room2pipes2",
		path = "GFX\map\room2pipes2_opt.rmesh",
		zone1 = 2,
		--disabledecals = true,
		commonness = 70,
		shape = "2",
		descr = "Another variant of the two-door hallway, with caged floors and ceiling that contain various pipes.",
	},
	checkpoint2 = {
		name = "checkpoint2",
		path = "GFX\map\checkpoint2_opt.rmesh",
		commonness = 0,
		shape = "2",
		descr = "The keycarded checkpoint which leads from the HCZ to the EZ.",
	},
	
	-- ENTRANCE ZONE ROOMS
	-- ============================
	
	room079 = {
		name = "room079",
		path = "GFX\map\room079_opt.rmesh",
		large = true,
		zone1 = 3,
		--disabledecals = true,
		commonness = 0,
		shape = "1",
		descr = "SCP-079's containment chamber.",
	},
	lockroom2 = {
		name = "lockroom2",
		path = "GFX\map\lockroom2_opt.rmesh",
		zone1 = 3,
		commonness = 0,
		shape = "2C",
		descr = "The open-doored lockroom, with SCP-096 sitting in the middle.",
	},
	endroom3 = {
		name = "endroom3",
		path = "GFX\map\endroom3_opt.rmesh",
		zone1 = 3,
		commonness = 100,
		shape = "1",
		descr = "Red-lit dead end room with a large, unopenable gate. EZ variant.",
	},
	exit1 = {
		name = "exit1",
		path = "GFX\map\exit1_opt.rmesh",
		zone1 = 3,
		disableoverlapcheck = true,
		commonness = 0,
		shape = "1",
		descr = "The entrance room to Gate B, with an elevator to the surface of Gate B.",
	},
	gateaentrance = {
		name = "gateaentrance",
		path = "GFX\map\gateaentrance_opt.rmesh",
		zone1 = 3,
		commonness = 0,
		shape = "1",
		descr = "The room with the elevator to Gate A.",
	},
	gatea = {
		name = "gatea",
		path = "GFX\map\gatea_opt.rmesh",
		disableoverlapcheck = true,
		commonness = 0,
		shape = "1",
		descr = "The surface of Gate A. Placed automatically in every map.",
	},
	medibay = {
		name = "medibay",
		path = "GFX\map\medibay_opt.rmesh",
		zone1 = 3,
		commonness = 0,
		shape = "2",
		descr = "A two-door hallway, leading to the medical bay. Contains a zombie.",
	},
	room2z3 = {
		name = "room2z3",
		path = "GFX\map\room2z3_opt.rmesh",
		zone1 = 3,
		commonness = 75,
		shape = "2",
		descr = "An office-styled two-door hallway.",
	},
	room2cafeteria = {
		name = "room2cafeteria",
		path = "GFX\map\room2cafeteria_opt.rmesh",
		zone1 = 3,
		large = true,
		--disabledecals = true,
		commonness = 0,
		shape = "2",
		descr = "A two-doored walkway, with stairs leading to the cafeteria.",
	},
	room2Cz3 = {
		name = "room2Cz3",
		path = "GFX\map\room2Cz3_opt.rmesh",
		zone1 = 3,
		commonness = 100,
		shape = "2C",
		descr = "A corner room, with two benches against the walls.",
	},
	room2ccont = {
		name = "room2ccont",
		path = "GFX\map\room2ccont_opt.rmesh",
		large = true,
		zone1 = 3,
		commonness = 0,
		shape = "2C",
		descr = "A corner room, which has the electrical center. Required to finish the game.",
	},
	room2offices = {
		name = "room2offices",
		path = "GFX\map\room2offices_opt.rmesh",
		zone1 = 3,
		commonness = 30,
		shape = "2",
		descr = "A small, plain office room with various deks.",
	},
	room2offices2 = {
		name = "room2offices2",
		path = "GFX\map\room2offices2_opt.rmesh",
		zone1 = 3,
		--disabledecals = true,
		commonness = 20,
		shape = "2",
		descr = "An office room with stairs that extends downwards.",
	},
	room2offices3 = {
		name = "room2offices3",
		path = "GFX\map\room2offices3_opt.rmesh",
		zone1 = 3,
		commonness = 20,
		shape = "2",
		descr = "A large office with a second floor, and two seperate rooms.",
	},
	room2offices4 = {
		name = "room2offices4",
		path = "GFX\map\room2offices4_opt.rmesh",
		zone1 = 3,
		commonness = 0,
		shape = "2",
		descr = "A varient of the offices.",
	},
	room2poffices = {
		name = "room2poffices",
		path = "GFX\map\room2poffices_opt.rmesh",
		zone1 = 3,
		commonness = 0,
		shape = "2",
		descr = "A two-door hallway with three labeled offices (Harp, Maynard, & Gears).",
	},
	room2poffices2 = {
		name = "room2poffices2",
		path = "GFX\map\room2poffices2_opt.rmesh",
		zone1 = 3,
		commonness = 0,
		shape = "2",
		descr = "A smaller hallway, with two doors leading to Dr. L's office and the conference rooms.",
	},
	room2sroom = {
		name = "room2sroom",
		path = "GFX\map\room2sroom_opt.rmesh",
		zone1 = 3,
		commonness = 0,
		shape = "2",
		descr = "A two-door hallway with an office containing SCP-420-J",
	},
	room2toilets = {
		name = "room2toilets",
		path = "GFX\map\room2toilets_opt.rmesh",
		zone1 = 3,
		commonness = 30,
		shape = "2",
		descr = "Hallway containing SCP-789-J.",
	},
	room2tesla = {
		name = "room2tesla",
		path = "GFX\map\room2tesla_opt.rmesh",
		zone1 = 3,
		commonness = 100,
		shape = "2",
		descr = "Hallway with a tesla gate. EZ variant.",
	},
	room3servers = {
		name = "room3servers",
		path = "GFX\map\room3servers_opt.rmesh",
		zone1 = 3,
		--disabledecals = true,
		commonness = 0,
		shape = "3",
		descr = "A maze of re-arranced servers, where SCP-173 spawns.",
	},
	room3servers2 = {
		name = "room3servers2",
		path = "GFX\map\room3servers2_opt.rmesh",
		zone1 = 3,
		--disabledecals = true,
		commonness = 0,
		shape = "3",
		descr = "Another variant of the server room, with a longer catwalk.",
	},
	room3z3 = {
		name = "room3z3",
		path = "GFX\map\room3z3_opt.rmesh",
		zone1 = 3,
		commonness = 100,
		shape = "3",
		descr = "A three-door hallway.",
	},
	room4z3 = {
		name = "room4z3",
		path = "GFX\map\room4z3_opt.rmesh",
		zone1 = 3,
		commonness = 100,
		shape = "4",
		descr = "A 4-door hallway.",
	},
	room1lifts = {
		name = "room1lifts",
		path = "GFX\map\room1lifts_opt.rmesh",
		zone1 = 3,
		commonness = 0,
		shape = "1",
		descr = "A dead-end room with two elevators.",
	},
	room3gw = {
		name = "room3gw",
		path = "GFX\map\room3gw_opt.rmesh",
		zone1 = 3,
		commonness = 10,
		shape = "3",
		descr = "An alternate, EZ-styled, broken contamination airlock.",
	},
	room2servers2 = {
		name = "room2servers2",
		path = "GFX\map\room2servers2_opt.rmesh",
		zone1 = 3,
		commonness = 0,
		shape = "2",
		descr = "A server room dedicated to keep the Site-COMmunications up and running (no real value).",
	},
	room3offices = {
		name = "room3offices",
		path = "GFX\map\room3offices_opt.rmesh",
		zone1 = 3,
		commonness = 0,
		shape = "3",
		descr = "A office room with three exits.",
	},
	room2z3_2 = {
		name = "room2z3_2",
		path = "GFX\map\room2z3_2_opt.rmesh",
		zone1 = 3,
		commonness = 25,
		shape = "2",
		descr = "A varient of the two-door hallway.",
	},
	pocketdimension = {
		name = "pocketdimension",
		path = "GFX\map\pocketdimension1_opt.rmesh",
		commonness = 0,
		shape = "1",
		descr = "SCP-106's pocket dimension. Placed automatically in all maps.",
	},
	dimension1499 = {
		name = "dimension1499",
		path = "GFX\map\dimension1499\1499object0_opt.rmesh",
		--disabledecals = true,
		commonness = 0,
		shape = "1",
		descr = "SCP-1499's dimension. Placed automatically in all maps.",
		disableoverlapcheck = true
	},
}

return RoomsModule
